### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by rdebath** [cv-robo/brainfuck#1]
This program should print "Hello World!", however, your loop constructs are incorrect.

``` bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by cv-robo** [comment]
> This program should print "Hello World!", however, your loop constructs are incorrect.
> 
> ```bf
> +[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
> >>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
> ```

Thanks. You are right.
Now the problem seems to have been fixed.

**Comment by rdebath** [comment]
Interestingly this one is failing now; it should be printing "Brainfuck " but it just says "Brain".

``` bf
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++.---
    ------[>++<-]>.<++++[>----<-]>-.++++++++.+++++.[-]<++++[->++++<]>+[-<+
    +++++>]<.+++++++++++++++.>++++++[<--->-]<.++++++++.--[--->+<]>---.[-]<
```

**Comment by cv-robo** [comment]
> Interestingly this one is failing now; it should be printing "Brainfuck " but it just says "Brain".
> 
> ```bf
>     ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++.---
>     ------[>++<-]>.<++++[>----<-]>-.++++++++.+++++.[-]<++++[->++++<]>+[-<+
>     +++++>]<.+++++++++++++++.>++++++[<--->-]<.++++++++.--[--->+<]>---.[-]<
> ```

Fixed.
